/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface AlembicVersion {
  version_num: string;
}

export interface DB {
  alembic_version: AlembicVersion;
}
